Repository JoseAugustoJasfarias/bibliotech, pull requests merged in 2023-04, with the labels that each got.

#17 Implementação da autenticação de login com o Facebook
  src/assets/icons/facebook.svg
  src/components/Menu/Menu.jsx
  src/firebase/auth.js
  src/pages/Login/Login.jsx
Labels: bug, documentation, enhancement

#19 Implementação de autenticação de login com facebook na pagina Cadastro
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Login/Login.jsx
Labels: bug, documentation, enhancement

#20 Implementação de verificação de status atual para atrasado automaticamente, Inclusão …
  package-lock.json
  package.json
  src/pages/AdicionarEmprestimo/AdicionarEmprestimo.jsx
  src/pages/EditarEmprestimo/EditarEmprestimo.jsx
  src/pages/EditarLivro/EditarLivro.jsx
  src/pages/Emprestimos/Emprestimos.jsx
Labels: documentation, enhancement

#23 Implementação de verificação de status atual para atrasado, Inclusão …
  src/App.jsx
Labels: documentation, enhancement

#26 implementação tema claro e escuro
  src/App.jsx
  src/components/Menu/Menu.jsx
  src/contexts/ThemeContext.js
  src/pages/AdicionarEmprestimo/AdicionarEmprestimo.jsx
  src/pages/AdicionarLivro/AdicionarLivro.jsx
  src/pages/Ajuda/Ajuda.jsx
  src/pages/EditarEmprestimo/EditarEmprestimo.jsx
  src/pages/EditarLivro/EditarLivro.jsx
  src/pages/Emprestimos/Emprestimos.jsx
  src/pages/Home/Home.jsx
  src/pages/Livros/Livros.jsx
  src/pages/Root/Root.jsx
Labels: documentation, enhancement

#29 Implementação do compomente de Splash ao atualizar a página
  src/App.jsx
  src/components/Menu/Menu.css
  src/components/Menu/Menu.jsx
Labels: documentation, enhancement

#31 homecx
  src/pages/Home/Home.jsx
Labels: documentation, enhancement

#32 Implementação da Autenticação para Cadastro e Login com o GitHub
  src/assets/icons/github.svg
  src/firebase/auth.js
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Login/Login.css
  src/pages/Login/Login.jsx
Labels: documentation, enhancement

#33 criação do quizz nas paginas publicas
  src/App.jsx
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Home/Home.css
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/Quizz/Quizz.css
  src/pages/Quizz/Quizz.jsx
Labels: documentation, enhancement

#38 Implementação de menu para alterar o status do livro na página Empres…
  src/pages/Emprestimos/Emprestimos.css
  src/pages/Emprestimos/Emprestimos.jsx
Labels: documentation, enhancement

#40 criação da página notFound
  src/App.jsx
  src/components/Menu/Menu.jsx
  src/pages/Home/Home.css
  src/pages/NotFound/NotFound.css
  src/pages/NotFound/NotFound.jsx
Labels: documentation, enhancement

#44 Implementação para amostra de mensagens de verificação para erros
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Login/Login.jsx
Labels: documentation, enhancement

#46 implementação do breadcrumb nas paginas
  src/components/Breadcrumb/Breadcrumb.css
  src/components/Breadcrumb/Breadcrumb.jsx
  src/pages/AdicionarEmprestimo/AdicionarEmprestimo.jsx
  src/pages/AdicionarLivro/AdicionarLivro.jsx
  src/pages/Ajuda/Ajuda.jsx
  src/pages/EditarEmprestimo/EditarEmprestimo.jsx
  src/pages/EditarLivro/EditarLivro.jsx
  src/pages/Emprestimos/Emprestimos.jsx
  src/pages/Livros/Livros.jsx
  src/pages/Login/Login.jsx
  src/pages/Root/Root.jsx
Labels: documentation, enhancement

#47 Implementação do espelhamento de dados entre authentication e firesto…
  src/firebase/auth.js
  src/firebase/collections.js
  src/firebase/criarNovoUsuario.js
Labels: documentation, enhancement

#48 Mais detalhes sobre o livro#14
  src/pages/Livros/Livros.jsx
Labels: documentation, enhancement

#51 Recuperação do código de mostrar senha
  .vscode/launch.json
  package-lock.json
  package.json
  src/components/Menu/Menu.jsx
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Login/Login.jsx
Labels: bug

#53 postagem
  package-lock.json
  package.json
  src/App.jsx
  src/components/Menu/Menu.jsx
  src/pages/Ajuda/Ajuda.jsx
  src/pages/Postagem/Postagem.css
  src/pages/Postagem/Postagem.jsx
Labels: documentation, enhancement

#56 estilização final da pagina
  src/assets/images/BIBLIOTECH-login.png
  src/assets/images/BIBLIOTECH-navbar.png
  src/assets/video/BIBLIOTECH.gif
  src/components/Breadcrumb/Breadcrumb.jsx
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/Menu/Menu.css
  src/components/Menu/Menu.jsx
  src/pages/AdicionarEmprestimo/AdicionarEmprestimo.css
  src/pages/AdicionarEmprestimo/AdicionarEmprestimo.jsx
  src/pages/AdicionarLivro/AdicionarLivro.css
  src/pages/AdicionarLivro/AdicionarLivro.jsx
  src/pages/Ajuda/Ajuda.css
  src/pages/Ajuda/Ajuda.jsx
  src/pages/Cadastro/Cadastro.jsx
  src/pages/EditarEmprestimo/EditarEmprestimo.css
  src/pages/EditarEmprestimo/EditarEmprestimo.jsx
  src/pages/EditarLivro/EditarLivro.css
  src/pages/EditarLivro/EditarLivro.jsx
  src/pages/Emprestimos/Emprestimos.css
  src/pages/Emprestimos/Emprestimos.jsx
  src/pages/Home/Home.css
  src/pages/Home/Home.jsx
  src/pages/Livros/Livros.css
  src/pages/Livros/Livros.jsx
  src/pages/Login/Login.jsx
  src/pages/NotFound/NotFound.jsx
  src/pages/Postagem/Postagem.css
  src/pages/Postagem/Postagem.jsx
  src/pages/Quizz/Quizz.css
  src/pages/Quizz/Quizz.jsx
Labels: documentation, enhancement
